# Generated by Django 4.1.7 on 2023-10-24 23:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmessage',
            name='message',
            field=ckeditor.fields.RichTextField(max_length=20000),
        ),
    ]
