# Generated by Django 4.1.7 on 2023-10-24 23:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_newmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='newmessage',
            name='message',
            field=models.TextField(max_length=20000),
        ),
    ]
